----- Begin Fatal Exception 18-Oct-2023 21:00:54 EDT-----------------------
An exception of category 'StdException' occurred while
   [0] Processing the python configuration file named EECs/test/test_EEC_AOD.py
Exception Message:
A std::exception was thrown.
File "EECs/test/test_EEC_AOD.py" could not be opened!
----- End Fatal Exception -------------------------------------------------
